    permissions:
      id-token: write
      contents: read

    - name: Configure AWS Credentials region audience
      uses: aws-actions/configure-aws-credentials@v4
      with:
        audience: sts.amazonaws.com
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::767397826387:role/ECR_push_role